name: decode-dna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11          # modern Python that Bioconda supports
  - pip                   # to run pip installs
  - nanofilt=2.8.0        # to filter quality and length if needed
  - cutadapt              # primer trimming
  - kraken2               # quick look taxonomic classification
  - vsearch               # clustering / dereplication
  - cd-hit                # sequence clustering
  - blast                 # NCBI BLAST+
  - taxonkit              # taxonomy utilities
  - seqkit                # FASTA/Q utilities
  - krona                 # interactive HTML taxonomic charts
  - pod5                  # convert legacy fast5 to pod5
  - clang_osx-64          # for building Bracken on macOS
  - llvm-openmp           # OpenMP support for clang

  # everything below will be installed by pip:
  - pip:
    - edlib
    - biopython
    - matplotlib

# Usage:
#   conda env create -f environment.yml
#   conda activate decode-dna

# The following will be installed manually (outside Conda):
  # - r-base
  # - r-tidyverse
  # - dorado
  # - amplicon_sorter
  # - ONTBarcoder
